version:  '2.1'
services:
  # SPRING CLOUD CONFIGURATION SERVICE
  configuration-service:
    image: fwsbac/configuration-service
    ports:
      - "32844:8888"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health.json"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      # Define these in your host machine environment
      - CONFIG_SERVICE_REPO
      - GIT_USER
      - GIT_PASSWORD
      - ENCRYPT_KEY
      - JAVA_OPTS=${CONTAINER_JAVA_OPTS}

  # TDS_StudentService
  student:
    image: fwsbac/tds-student-service
    ports:
      - "32840:8080"
    depends_on:
      configuration-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health.json"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - tds-common.env
      - student.env
    environment:
      - JAVA_OPTS=${CONTAINER_JAVA_OPTS}

  #TDS_AssessmentService
  assessment:
    image: fwsbac/tds-assessment-service
    ports:
      - "32841:8080"
    depends_on:
      configuration-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health.json"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - tds-common.env
      - assessment.env
    environment:
      - JAVA_OPTS=${CONTAINER_JAVA_OPTS}

  #TDS_SessionService
  session:
    image: fwsbac/tds-session-service
    ports:
      - "32842:8080"
    depends_on:
      configuration-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health.json"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - tds-common.env
      - session.env
    environment:
      - JAVA_OPTS=${CONTAINER_JAVA_OPTS}

  #TDS_ConfigService
  config:
    image: fwsbac/tds-config-service
    ports:
      - "32843:8080"
    depends_on:
      configuration-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health.json"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - tds-common.env
      - config.env
    environment:
      - JAVA_OPTS=${CONTAINER_JAVA_OPTS}

  #TDS Equation Scoring Engine
  equation-scoring-image:
    image: fwsbac/equation-scoring-image:3.0.0
    ports:
      - "32845:8080"

  #TDS_ExamService
  exam:
    image: fwsbac/tds-exam-service
    ports:
      - "80:8080"
    depends_on:
      configuration-service:
        condition: service_healthy
      assessment:
        condition: service_started
      session:
        condition: service_started
      student:
        condition: service_started
      config:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health.json"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - tds-common.env
      - exam.env
    environment:
      # Define these in your host machine environment
      - SBAC_JDBC_HOST
      - SBAC_JDBC_USER
      - SBAC_JDBC_PASSWORD
      - JAVA_OPTS=${CONTAINER_JAVA_OPTS}

