version:  '2.1'
services:
  configuration-service:
    image: fwsbac/configuration-service
    ports:
      - "32844:8888"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health.json"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      # Define these in your host machine environment
      - CONFIG_SERVICE_REPO
      - GIT_USER
      - GIT_PASSWORD
      - ENCRYPT_KEY
  student:
    image: fwsbac/tds-student-service
    ports:
      - "32840:8080"
    env_file: tds-docker.env
  assessment:
    image: fwsbac/tds-assessment-service
    ports:
      - "32841:8080"
    env_file: tds-docker.env
  session:
    image: fwsbac/tds-session-service
    ports:
      - "32842:8080"
    env_file: tds-docker.env
  config:
    image: fwsbac/tds-config-service
    ports:
      - "32843:8080"
    env_file: tds-docker.env
  exam:
    image: fwsbac/tds-exam-service
    ports:
      - "80:8080"
    depends_on:
      configuration-service:
        condition: service_healthy
      assessment:
        condition: service_started
      session:
        condition: service_started
      student:
        condition: service_started
      config:
        condition: service_started
    environment:
      - CONFIG_SERVICE_URL=http://configuration-service:8888
      - CONFIG_SERVICE_ENABLED=true
      - SPRING_PROFILES_ACTIVE=local-docker
      # Define these in your host machine environment
      - MYSQL_URL
      - MYSQL_USER
      - MYSQL_PASSWORD
